# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomLayout-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomLayout-Swift
    pod 'SnapKit'
  target 'CustomLayout-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomLayout-SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
